### ISSUE TITLE
All of the tests fail

### ISSUE THREAD

**Issue by StephenTrombetti** [snicoll-demos/demo-multi-entity-managers#4]
Steps to repeat

    git clone
    cd demo-multi-entity-manager
    mvn clean test

**Comment by snicoll** [comment]
They don't for me. If you want some help you need a bit more details than this.

**Comment by StephenTrombetti** [comment]
Hi, Sorry for the red flag. I've gotten this to work now. Before posting I tried to run the tests on two separate machines to confirm that it wasn't a local issue - turns out it still was. After your post I forked and confirmed that it works with TravisCI. So I went back to my machines and found that one was using Java 9 which causes API issues and the other had corrupt jar files in the maven repo which causes ClassDefNotFoundErrors.
